# Generated by Django 4.0.4 on 2022-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=100)),
                ('password', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
